{
  "textPayload": "The request failed because either the HTTP response was malformed or connection to the instance had an error. Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#malformed-response-or-connection-error",
  "insertId": "67da11e80007938ee630d1df",
  "httpRequest": {
    "requestMethod": "GET",
    "requestUrl": "https://palios-taey-yb6xskdufa-uc.a.run.app/",
    "requestSize": "556",
    "status": 503,
    "responseSize": "67",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3.1 Safari/605.1.15",
    "remoteIp": "73.56.93.57",
    "serverIp": "216.239.38.53",
    "latency": "0.836184259s",
    "protocol": "HTTP/1.1"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "project_id": "palios-taey-dev",
      "service_name": "palios-taey",
      "location": "us-central1",
      "configuration_name": "palios-taey",
      "revision_name": "palios-taey-00006-nrc"
    }
  },
  "timestamp": "2025-03-19T00:37:59.648417Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00fd7d73376e3dcd773595db35cc9bfcd43c9682a144d558f22067bcf738b658a056fecf11d468e6827de22aa8df6bc7442a733d4c460b481ec182406466f4277bdea90c41"
  },
  "logName": "projects/palios-taey-dev/logs/run.googleapis.com%2Frequests",
  "trace": "projects/palios-taey-dev/traces/2dd06d6676354eaf5b65edf52517595b",
  "receiveTimestamp": "2025-03-19T00:38:00.508959338Z",
  "spanId": "b8b926aad515fbbc",
  "traceSampled": true
}

{
  "textPayload": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py\", line 608, in spawn_worker\n    worker.init_process()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py\", line 94, in init_process\n    super().init_process()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py\", line 135, in init_process\n    self.load_wsgi()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py\", line 147, in load_wsgi\n    self.wsgi = self.app.wsgi()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py\", line 66, in wsgi\n    self.callable = self.load()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py\", line 57, in load\n    return self.load_wsgiapp()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py\", line 47, in load_wsgiapp\n    return util.import_app(self.app_uri)\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/util.py\", line 370, in import_app\n    mod = importlib.import_module(module)\n  File \"/usr/local/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n  File \"/app/src/main.py\", line 13, in <module>\n    from environment_config import initialize_environment\nModuleNotFoundError: No module named 'environment_config'",
  "insertId": "67da11e800060c7317dfe676",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "service_name": "palios-taey",
      "location": "us-central1",
      "project_id": "palios-taey-dev",
      "configuration_name": "palios-taey",
      "revision_name": "palios-taey-00006-nrc"
    }
  },
  "timestamp": "2025-03-19T00:38:00.396403Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00fd7d73376e3dcd773595db35cc9bfcd43c9682a144d558f22067bcf738b658a056fecf11d468e6827de22aa8df6bc7442a733d4c460b481ec182406466f4277bdea90c41"
  },
  "logName": "projects/palios-taey-dev/logs/run.googleapis.com%2Fstderr",
  "receiveTimestamp": "2025-03-19T00:38:00.403873368Z",
  "errorGroups": [
    {
      "id": "CKuxgdDAnuj3Qg"
    }
  ]
}

{
  "textPayload": "The request failed because either the HTTP response was malformed or connection to the instance had an error. Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#malformed-response-or-connection-error",
  "insertId": "67da11f2000a149fec6365aa",
  "httpRequest": {
    "requestMethod": "GET",
    "requestUrl": "https://palios-taey-yb6xskdufa-uc.a.run.app/health",
    "requestSize": "537",
    "status": 503,
    "responseSize": "67",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3.1 Safari/605.1.15",
    "remoteIp": "73.56.93.57",
    "serverIp": "216.239.38.53",
    "latency": "1.105213574s",
    "protocol": "HTTP/1.1"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "location": "us-central1",
      "service_name": "palios-taey",
      "revision_name": "palios-taey-00006-nrc",
      "project_id": "palios-taey-dev",
      "configuration_name": "palios-taey"
    }
  },
  "timestamp": "2025-03-19T00:38:09.420648Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00fd7d7337f4e02c1a23d796353da82c57f6a1de4b2f9c5f44b73dbacf228781459b61b035280c9aa45bb0ceb9f3a3ae9eaf1b8d4b6a9db81d376f5593b0fa78ba4c58d220"
  },
  "logName": "projects/palios-taey-dev/logs/run.googleapis.com%2Frequests",
  "trace": "projects/palios-taey-dev/traces/ffffc0bf846a962ba4c951178ae1e3de",
  "receiveTimestamp": "2025-03-19T00:38:10.823916807Z",
  "spanId": "7f33b33a69244e2d"
}
{
  "textPayload": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py\", line 608, in spawn_worker\n    worker.init_process()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py\", line 94, in init_process\n    super().init_process()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py\", line 135, in init_process\n    self.load_wsgi()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py\", line 147, in load_wsgi\n    self.wsgi = self.app.wsgi()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py\", line 66, in wsgi\n    self.callable = self.load()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py\", line 57, in load\n    return self.load_wsgiapp()\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py\", line 47, in load_wsgiapp\n    return util.import_app(self.app_uri)\n  File \"/usr/local/lib/python3.10/site-packages/gunicorn/util.py\", line 370, in import_app\n    mod = importlib.import_module(module)\n  File \"/usr/local/lib/python3.10/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n  File \"/app/src/main.py\", line 13, in <module>\n    from environment_config import initialize_environment\nModuleNotFoundError: No module named 'environment_config'",
  "insertId": "67da11f200087d40cc9a03fa",
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "location": "us-central1",
      "configuration_name": "palios-taey",
      "revision_name": "palios-taey-00006-nrc",
      "project_id": "palios-taey-dev",
      "service_name": "palios-taey"
    }
  },
  "timestamp": "2025-03-19T00:38:10.556352Z",
  "severity": "ERROR",
  "labels": {
    "instanceId": "00fd7d7337f4e02c1a23d796353da82c57f6a1de4b2f9c5f44b73dbacf228781459b61b035280c9aa45bb0ceb9f3a3ae9eaf1b8d4b6a9db81d376f5593b0fa78ba4c58d220"
  },
  "logName": "projects/palios-taey-dev/logs/run.googleapis.com%2Fstderr",
  "receiveTimestamp": "2025-03-19T00:38:10.727866876Z",
  "errorGroups": [
    {
      "id": "CKuxgdDAnuj3Qg"
    }
  ]
}

